### ISSUE TITLE
Update needed in SeleniumStarter iml e pom.xml

### ISSUE THREAD

**Issue by andremilk** [CodeSolid/tutorials#2]
The current version of firefox and selenium 2.41 don't get along, the fix is just to replace the version of selenium to 2.5. Also, great tutorial, thanks!

**Comment by JohnLockwood** [comment]
Wow, @andremilk sorry it's taken me so long to reply -- I've been away from this project too long.  Anyway, I checked in the fixes to get it working as of my latest attempt.  Thanks for the issue and the kind words.
